"""empty message

Revision ID: 0026836db3b1
Revises: 7420138af795
Create Date: 2025-06-26 07:04:03.290039

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0026836db3b1'
down_revision = '7420138af795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('rating', sa.Column('rater_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'rating', 'user', ['rater_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'rater_id')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###
