"""empty message

Revision ID: 028007b3aba9
Revises: 8369acba1253
Create Date: 2025-06-26 06:50:17.917016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '028007b3aba9'
down_revision = '8369acba1253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
