"""empty message

Revision ID: 0f2831d0109e
Revises: e24156c8dbec
Create Date: 2025-06-26 21:41:50.808650

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f2831d0109e'
down_revision = 'e24156c8dbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('time_of_arrival', sa.DateTime(), nullable=False))
    op.drop_column('ride', 'time_of_arrial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('time_of_arrial', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('ride', 'time_of_arrival')
    # ### end Alembic commands ###
