"""empty message

Revision ID: 206b37e481d9
Revises: 2c2653e66634
Create Date: 2025-06-28 01:11:09.607359

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '206b37e481d9'
down_revision = '2c2653e66634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('car', sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('car', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('car', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('car', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('car', 'license_plate')
    op.drop_column('car', 'color')
    # ### end Alembic commands ###
