"""empty message

Revision ID: 2c2653e66634
Revises: 8e4f58d9bb3c
Create Date: 2025-06-28 00:39:50.993376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c2653e66634'
down_revision = '8e4f58d9bb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
