"""empty message

Revision ID: 2d237d6ae943
Revises: b106a50fdc9b
Create Date: 2025-06-27 20:01:18.260755

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d237d6ae943'
down_revision = 'b106a50fdc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('n_codrives', sa.Integer(), nullable=False))
    op.add_column('ride', sa.Column('max_n_codrives', sa.Integer(), nullable=False))
    op.drop_column('ride', 'n_co_driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('n_co_driver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ride', 'max_n_codrives')
    op.drop_column('ride', 'n_codrives')
    # ### end Alembic commands ###
