"""empty message

Revision ID: 34c3287856d5
Revises: 97ecbb5afa7e
Create Date: 2025-06-26 06:40:55.137396

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34c3287856d5'
down_revision = '97ecbb5afa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'stop', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop', type_='foreignkey')
    op.drop_column('stop', 'location_id')
    # ### end Alembic commands ###
