"""empty message

Revision ID: 38b2545bfb85
Revises: fa4ed70c8e13
Create Date: 2025-06-26 06:47:41.377354

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '38b2545bfb85'
down_revision = 'fa4ed70c8e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_rater_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'rater_id')
    op.drop_column('user', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('rating', sa.Column('rater_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('rating_rater_id_fkey', 'rating', 'user', ['rater_id'], ['id'])
    # ### end Alembic commands ###
