"""empty message

Revision ID: 3b578b1bb69a
Revises: 34c3287856d5
Create Date: 2025-06-26 06:41:19.925830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b578b1bb69a'
down_revision = '34c3287856d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('start_location_id', sa.Uuid(), nullable=False))
    op.add_column('ride', sa.Column('end_location_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'ride', 'location', ['end_location_id'], ['id'])
    op.create_foreign_key(None, 'ride', 'location', ['start_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.drop_column('ride', 'end_location_id')
    op.drop_column('ride', 'start_location_id')
    # ### end Alembic commands ###
