"""empty message

Revision ID: 479094c7a3d3
Revises: 7429c49c7ac5
Create Date: 2025-06-28 22:05:55.085044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '479094c7a3d3'
down_revision = '7429c49c7ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_license', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_license')
    # ### end Alembic commands ###
