"""empty message

Revision ID: 5943c978f1f6
Revises: 2d237d6ae943
Create Date: 2025-06-29 11:25:08.595430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5943c978f1f6'
down_revision = '2d237d6ae943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codrive', sa.Column('route_update', sa.JSON(), nullable=True))
    op.add_column('ride', sa.Column('prefer_starting_time', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'prefer_starting_time')
    op.drop_column('codrive', 'route_update')
    # ### end Alembic commands ###
