"""empty message

Revision ID: 5a8ae9673bf1
Revises: 14ec042d92cc
Create Date: 2025-06-27 11:46:24.496008

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a8ae9673bf1'
down_revision = '14ec042d92cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ride', 'recurring_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ride', 'recurring_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
