"""empty message

Revision ID: 613dded6293e
Revises: ba134724e978
Create Date: 2025-06-26 07:00:03.762875

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '613dded6293e'
down_revision = 'ba134724e978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'car', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'owner_id')
    # ### end Alembic commands ###
