"""empty message

Revision ID: 7420138af795
Revises: 804a6eb4468c
Create Date: 2025-06-26 07:02:46.440852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7420138af795'
down_revision = '804a6eb4468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_location_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_location_id_fkey', 'user', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###
