"""empty message

Revision ID: 7429c49c7ac5
Revises: 206b37e481d9
Create Date: 2025-06-28 21:59:31.643269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7429c49c7ac5'
down_revision = '206b37e481d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
