"""empty message

Revision ID: 74a78169975d
Revises: fa9c359ca9cf
Create Date: 2025-06-26 06:39:50.338279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '74a78169975d'
down_revision = 'fa9c359ca9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('car_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'ride', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.drop_column('ride', 'car_id')
    # ### end Alembic commands ###
