"""empty message

Revision ID: 756b711a755c
Revises: fbeb3a1e022a
Create Date: 2025-06-26 06:37:31.808978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '756b711a755c'
down_revision = 'fbeb3a1e022a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_rater_id_fkey', 'rating', type_='foreignkey')
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'rater_id')
    op.drop_column('rating', 'user_id')
    op.drop_constraint('stop_user_id_fkey', 'stop', type_='foreignkey')
    op.drop_column('stop', 'user_id')
    op.drop_column('user', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('stop', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('stop_user_id_fkey', 'stop', 'user', ['user_id'], ['id'])
    op.add_column('rating', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('rating', sa.Column('rater_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user', ['user_id'], ['id'])
    op.create_foreign_key('rating_rater_id_fkey', 'rating', 'user', ['rater_id'], ['id'])
    # ### end Alembic commands ###
