"""empty message

Revision ID: 804a6eb4468c
Revises: 613dded6293e
Create Date: 2025-06-26 07:00:54.364111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '804a6eb4468c'
down_revision = '613dded6293e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'location_id')
    # ### end Alembic commands ###
