"""empty message

Revision ID: 8369acba1253
Revises: aa4c1161fd21
Create Date: 2025-06-26 06:49:50.071515

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8369acba1253'
down_revision = 'aa4c1161fd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
