"""empty message

Revision ID: 8befdaf10119
Revises: 02c363d7ff92
Create Date: 2025-06-26 13:18:39.712338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8befdaf10119'
down_revision = '02c363d7ff92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
