"""empty message

Revision ID: 94ff918024da
Revises: 0f2831d0109e
Create Date: 2025-06-26 21:48:26.025897

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94ff918024da'
down_revision = '0f2831d0109e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('location', sa.Column('longitude', sa.Float(), nullable=False))
    op.create_index(op.f('ix_location_latitude'), 'location', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_longitude'), 'location', ['longitude'], unique=False)
    op.add_column('ride', sa.Column('route_geometry', sa.JSON(), nullable=True))
    op.add_column('ride', sa.Column('estimated_duration_seconds', sa.Integer(), nullable=False))
    op.add_column('ride', sa.Column('estimated_distance_meters', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'estimated_distance_meters')
    op.drop_column('ride', 'estimated_duration_seconds')
    op.drop_column('ride', 'route_geometry')
    op.drop_index(op.f('ix_location_longitude'), table_name='location')
    op.drop_index(op.f('ix_location_latitude'), table_name='location')
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    # ### end Alembic commands ###
