"""empty message

Revision ID: 97ecbb5afa7e
Revises: 74a78169975d
Create Date: 2025-06-26 06:40:28.184184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '97ecbb5afa7e'
down_revision = '74a78169975d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('ride_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'stop', 'ride', ['ride_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop', type_='foreignkey')
    op.drop_column('stop', 'ride_id')
    # ### end Alembic commands ###
