"""empty message

Revision ID: 9a36dcb31cec
Revises: b1921bf13edd
Create Date: 2025-06-27 18:42:24.349514

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a36dcb31cec'
down_revision = 'b1921bf13edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
