"""empty message

Revision ID: af7d661ddf86
Revises: 2bd214f36547
Create Date: 2025-06-29 12:09:07.209044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af7d661ddf86'
down_revision = '2bd214f36547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'prefer_starting_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('prefer_starting_time', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
