"""empty message

Revision ID: b106a50fdc9b
Revises: 085dce9bf116
Create Date: 2025-06-27 18:57:49.364643

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b106a50fdc9b'
down_revision = '085dce9bf116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codrive', sa.Column('point_contribution', sa.Integer(), nullable=False))
    op.add_column('codrive', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.add_column('codrive', sa.Column('paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codrive', 'paid')
    op.drop_column('codrive', 'accepted')
    op.drop_column('codrive', 'point_contribution')
    # ### end Alembic commands ###
