"""empty message

Revision ID: b1921bf13edd
Revises: b9d4ab1f801b
Create Date: 2025-06-27 18:40:54.646773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1921bf13edd'
down_revision = 'b9d4ab1f801b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
