"""empty message

Revision ID: b27d541a7d0e
Revises: 3b578b1bb69a
Create Date: 2025-06-26 06:41:50.949606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b27d541a7d0e'
down_revision = '3b578b1bb69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ride_start_location_id_fkey', 'ride', type_='foreignkey')
    op.drop_constraint('ride_end_location_id_fkey', 'ride', type_='foreignkey')
    op.drop_column('ride', 'start_location_id')
    op.drop_column('ride', 'end_location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('end_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('start_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('ride_end_location_id_fkey', 'ride', 'location', ['end_location_id'], ['id'])
    op.create_foreign_key('ride_start_location_id_fkey', 'ride', 'location', ['start_location_id'], ['id'])
    # ### end Alembic commands ###
