"""empty message

Revision ID: b5577f2de75a
Revises: 8e4f58d9bb3c
Create Date: 2025-06-27 18:37:51.686284

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5577f2de75a'
down_revision = '8e4f58d9bb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codrive',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ride_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_arrival', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stop')
    op.drop_column('ride', 'recurring_tue')
    op.drop_column('ride', 'recurring_wed')
    op.drop_column('ride', 'recurring_sat')
    op.drop_column('ride', 'recurring_fri')
    op.drop_column('ride', 'recurring_thu')
    op.drop_column('ride', 'recurring_id')
    op.drop_column('ride', 'recurring_mon')
    op.drop_column('ride', 'recurring_sun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('recurring_sun', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_mon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ride', sa.Column('recurring_thu', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_fri', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_sat', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_wed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('recurring_tue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('stop',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_of_arrival', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ride_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='stop_location_id_fkey'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name='stop_ride_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='stop_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stop_pkey')
    )
    op.drop_table('codrive')
    # ### end Alembic commands ###
