"""empty message

Revision ID: c113add9b4fc
Revises: 5a8ae9673bf1
Create Date: 2025-06-27 11:53:11.947251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c113add9b4fc'
down_revision = '5a8ae9673bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
