"""empty message

Revision ID: cc2d2d7389df
Revises: b3c1b0ab37f8
Create Date: 2025-07-01 15:54:50.372000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc2d2d7389df'
down_revision = 'b3c1b0ab37f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
