"""empty message

Revision ID: fa9c359ca9cf
Revises: 756b711a755c
Create Date: 2025-06-26 06:39:03.487451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa9c359ca9cf'
down_revision = '756b711a755c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_owner_id_fkey', 'car', type_='foreignkey')
    op.drop_column('car', 'owner_id')
    op.drop_constraint('ride_car_id_fkey', 'ride', type_='foreignkey')
    op.drop_constraint('ride_driver_id_fkey', 'ride', type_='foreignkey')
    op.drop_column('ride', 'driver_id')
    op.drop_column('ride', 'car_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('car_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ride', sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('ride_driver_id_fkey', 'ride', 'user', ['driver_id'], ['id'])
    op.create_foreign_key('ride_car_id_fkey', 'ride', 'car', ['car_id'], ['id'])
    op.add_column('car', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('car_owner_id_fkey', 'car', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
