"""empty message

Revision ID: faed849ae2c8
Revises: 71e16aecd902
Create Date: 2025-06-26 07:06:51.941430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'faed849ae2c8'
down_revision = '71e16aecd902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'location_id')
    # ### end Alembic commands ###
