"""empty message

Revision ID: fb6cd954e51e
Revises: 38b2545bfb85
Create Date: 2025-06-26 06:48:13.891354

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fb6cd954e51e'
down_revision = '38b2545bfb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
